global:
  scrape_interval: 15s   # Her 15 saniyede bir scrape yapılacak
  evaluation_interval: 15s

scrape_configs:
 # - job_name: 'place-service-logs'
  #  static_configs:
  #    - targets: [ 'loki:3100' ]
  #      labels:
   #       job: place-service
     #     __path__: /var/log/place-service/*.log

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics

  - job_name: 'car-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'car-service:8081' ]

  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'customer-service:8082' ]

  - job_name: 'reservation-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'reservation-service:8083' ]

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'payment-service:8084' ]

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
